### ISSUE TITLE
deploying own version

### ISSUE THREAD

**Issue by hyph3nx** [NatPDeveloper/eos-chess#2]
Hi,

Could you please help me with deploying my own version?
I forked then imported using heroku

Thanks

**Comment by NatPDeveloper** [comment]
Yeah, so I would first `npm install`.
Then create a .env file in root.  I have 2 places where the MongoDB url is set up.  One is in my app js, the other is in: https://github.com/NatPDeveloper/eos-chess/blob/master/js/lib/demux-js/updaters.js#L4

After that, you should be able to run `node app.js` and have it work.

If you're using heroku, I used mlabs to set up my mongo database, so you'd have to set up your own.

Feel free to hit me up on telegram as well: https://t.me/natpd
